@host = http://localhost:7700

GET {{host}}/books HTTP/1.1
content-type: application/json

###

GET {{host}}/books/1 HTTP/1.1
content-type: application/json

###

POST {{host}}/books/1 HTTP/1.1
content-type: application/json

{
  "isbn": "5",
  "author": "Robin Wieruch",
  "title": "The Road to React"
}


