@host = http://localhost:7700

GET {{host}}/api/v1/books HTTP/1.1
content-type: application/json

###

GET {{host}}/api/v1/books/1 HTTP/1.1
content-type: application/json

###

POST {{host}}/api/v1/books HTTP/1.1
content-type: application/json

{
  "isbn": "5",
  "author": "Markus Dethlefsen",
  "title": "deno first steps"
}


